name: Run Bullish 500 Screener

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  run-screener:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Create cred.json from secrets
        run: echo '${{ secrets.CRED_JSON }}' > cred.json
      
      - name: Run screener
        run: python HNR-Bullish500.py